# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]

featuredImageField = "image"
# Output page's full content in RSS.
rssFullContent = true

# e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)
favicon= "/favicon.ico"

[footer]
since = 2019
customText = "I just want a peaceful life without troubles"

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "🖥️"
subtitle = "Why there is a universe?"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[article]
math = true
toc = true
readingTime = true

[article.license]
enabled = true
default = "[Licensed under CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ml)" 


## Widgets
[widgets]
enabled = ["search", "archives", "tag-cloud"]

[widgets.archives]
limit = 5

[widgets.tagCloud]
limit = 10

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = "Chasing1020" # Your Twitter username
card = "summary_large_image" # Available values: summary, summary_large_image

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = false


## Comments
[comments]
enabled = true
provider = "giscus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = "Chasing1020/Chasing1020.github.io"
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = "Chasing1020/Chasing1020.github.io"
repoID = "R_kgDOGR5Ifw"
category = "General"
categoryID = "DIC_kwDOGR5If84CURCm"
mapping = "url"
lightTheme = "light"
darkTheme = "dark"
lang = "en"
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
